### ISSUE TITLE
Publish EntityFramework.Core 3.0 release on NuGet.

### ISSUE THREAD

**Issue by abbottdev** [googleapis/dotnet-spanner-entity-framework#460] opened 2024-10-21 09:07 UTC
The 3.0 release was created 2 weeks ago but it's not currently published on NuGet. 

Can we publish the release here: https://github.com/googleapis/dotnet-spanner-entity-framework/releases/tag/Google.Cloud.EntityFrameworkCore.Spanner-3.0.0 to NuGet?

**Comment by amanda-tarafa** [comment] 2024-11-06 19:59
We have no ETA at the moment, but we are actively working on it.

**Comment by amanda-tarafa** [comment] 2024-11-06 20:01
I'm closing this as duplicate of https://github.com/googleapis/dotnet-spanner-entity-framework/issues/459

**Closed by amanda-tarafa** 2024-11-06 20:01 UTC
Labels: type: feature request, priority: p3
